using Test
import OWENS

@testset "WindIO run spec paths" begin
    mktempdir() do dir
        model_file = joinpath(dir, "modeling_options.yml")
        windio_file = joinpath(dir, "design.yml")
        run_path = joinpath(dir, "run")
        write(model_file, "OWENS_Options:\n  numTS: 2\n")
        write(windio_file, "name: unit\n")
        mkdir(run_path)

        spec = OWENS.windio_run_spec(model_file, windio_file, run_path)
        @test spec isa OWENS.WindIORunSpec
        @test spec.modeling_options_file == abspath(model_file)
        @test spec.windio_file == abspath(windio_file)
        @test spec.run_path == abspath(run_path)

        created_run_path = joinpath(dir, "created_run")
        created_spec = OWENS.windio_run_spec(
            model_file,
            windio_file,
            created_run_path;
            create_run_path = true,
        )
        @test isdir(created_run_path)
        @test created_spec.run_path == abspath(created_run_path)

        @test_throws ArgumentError OWENS.windio_run_spec(
            joinpath(dir, "missing_model.yml"),
            windio_file,
            run_path,
        )
        @test_throws ArgumentError OWENS.windio_run_spec(
            model_file,
            joinpath(dir, "missing_design.yml"),
            run_path,
        )
        @test_throws ArgumentError OWENS.windio_run_spec(
            model_file,
            windio_file,
            joinpath(dir, "missing_run"),
        )
    end
end

@testset "WindIO run script export" begin
    mktempdir() do dir
        model_file = joinpath(dir, "modeling options.yml")
        windio_file = joinpath(dir, "design data.yml")
        run_path = joinpath(dir, "run path")
        script_file = joinpath(dir, "scripts", "run_windio.jl")
        write(model_file, "OWENS_Options:\n  numTS: 2\n")
        write(windio_file, "name: unit\n")
        mkdir(run_path)

        spec = OWENS.windio_run_spec(model_file, windio_file, run_path)
        expected_script = join(
            [
                "# Generated by OWENS.render_windio_run_script.",
                "using OWENS",
                "",
                "modeling_options_file = $(repr(abspath(model_file)))",
                "windio_file = $(repr(abspath(windio_file)))",
                "run_path = $(repr(abspath(run_path)))",
                "",
                "OWENS.runOWENSWINDIO(modeling_options_file, windio_file, run_path)",
                "",
            ],
            "\n",
        )

        @test OWENS.render_windio_run_script(spec) == expected_script
        written_script = OWENS.write_windio_run_script(script_file, spec)
        @test written_script == expected_script
        @test read(script_file, String) == expected_script
    end
end
