name: OWENS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy==1.19.2
  - scipy==1.5.2
  - capytaine==1.2
  - matplotlib
  - pip
  - pip:
    - pygmsh==6.1.0
    - meshmagick @ https://github.com/LHEEA/meshmagick/archive/2.0.tar.gz
