load("structDynInput.mat")
tic()
%Break Out Model
analysisType = model.analysisType;
turbineStartup = model.turbineStartup;
usingRotorSpeedFunction = model.usingRotorSpeedFunction;
tocp = model.tocp;
initCond = model.initCond;
numTS = model.numTS;
delta_t = model.delta_t;
Omegaocp = model.Omegaocp;
aeroElasticOn = model.aeroElasticOn;
aeroForceOn = model.aeroForceOn;
aeroLoadsOn = model.aeroLoadsOn;
driveTrainOn = model.driveTrainOn;
airDensity = model.airDensity;
guessFreq = model.guessFreq;
gravityOn = model.gravityOn;
generatorOn = model.generatorOn;
hydroOn = model.hydroOn;
JgearBox = model.JgearBox;
gearRatio = model.gearRatio;
gearBoxEfficiency = model.gearBoxEfficiency;
useGeneratorFunction = model.useGeneratorFunction;
generatorProps = model.generatorProps;
OmegaGenStart = model.OmegaGenStart;
omegaControl = model.omegaControl;
OmegaInit = model.OmegaInit;
totalNumDof = model.totalNumDof;
spinUpOn = false;
nlOn = model.nlOn;
numModesToExtract = 0;
aeroloadfile = model.aeroloadfile;
owensfile = model.owensfile;
outFilename = model.outFilename;
RayleighAlpha = model.RayleighAlpha;
RayleighBeta = model.RayleighBeta;
elementOrder = model.elementOrder;
joint = model.joint;
platformTurbineConnectionNodeNumber = model.platformTurbineConnectionNodeNumber;
jointTransform = model.jointTransform;
reducedDOFList = model.reducedDOFList;

bladeData = model.bladeData; %Struct
numBlades = bladeData.numBlades;
bladeNum = bladeData.bladeNum;
h = bladeData.h;
nodeNum = bladeData.nodeNum;
elementNum = bladeData.elementNum;
remaining = bladeData.remaining;

nlParams = model.nlParams; %Struct
iterationType = nlParams.iterationType;
adaptiveLoadSteppingFlag = nlParams.adaptiveLoadSteppingFlag;
tolerance = nlParams.tolerance;
maxIterations = nlParams.maxIterations;
maxNumLoadSteps = nlParams.maxNumLoadSteps;
minLoadStepDelta = nlParams.minLoadStepDelta;
minLoadStep = nlParams.minLoadStep;
prescribedLoadStep = nlParams.prescribedLoadStep;

BC = model.BC; %Struct
numpBC = BC.numpBC;
pBC = BC.pBC;
numsBC = BC.numsBC;
nummBC = BC.nummBC;
isConstrained = BC.isConstrained;
map = BC.map;
redVectorMap = BC.redVectorMap;

nodalTerms = model.nodalTerms; %Struct
concLoad = nodalTerms.concLoad;
concStiff = nodalTerms.concStiff;
concMass = nodalTerms.concMass;
concStiffGen = nodalTerms.concStiffGen;
concMassGen = nodalTerms.concMassGen;
concDampGen = nodalTerms.concDampGen;

driveShaftProps = model.driveShaftProps; %Struct
k = driveShaftProps.k;
c = driveShaftProps.c;

%Break out Mesh
nodeNummesh = mesh.nodeNum;
numEl = mesh.numEl;
numNodes = mesh.numNodes;
x = mesh.x;
y = mesh.y;
z = mesh.z;
elNum = mesh.elNum;
conn = mesh.conn;

%Break out el
props = el.props; %struct
ac = zeros(length(props),2);
twist = zeros(length(props),2);
rhoA = zeros(length(props),2);
EIyy = zeros(length(props),2);
EIzz = zeros(length(props),2);
GJ = zeros(length(props),2);
EA = zeros(length(props),2);
rhoIyy = zeros(length(props),2);
rhoIzz = zeros(length(props),2);
rhoJ = zeros(length(props),2);
zcm = zeros(length(props),2);
ycm = zeros(length(props),2);
a = zeros(length(props),2);
EIyz = zeros(length(props),2);
alpha1 = zeros(length(props),2);
alpha2 = zeros(length(props),2);
alpha3 = zeros(length(props),2);
alpha4 = zeros(length(props),2);
alpha5 = zeros(length(props),2);
alpha6 = zeros(length(props),2);
rhoIyz = zeros(length(props),2);
b = zeros(length(props),2);
a0 = zeros(length(props),2);
aeroCenterOffset = zeros(length(props),2);

for jj = 1:length(props)
    ac(jj,:) = props(jj).ac;
    twist(jj,:) = props(jj).twist;
    rhoA(jj,:) = props(jj).rhoA;
    EIyy(jj,:) = props(jj).EIyy;
    EIzz(jj,:) = props(jj).EIzz;
    GJ(jj,:) = props(jj).GJ;
    EA(jj,:) = props(jj).EA;
    rhoIyy(jj,:) = props(jj).rhoIyy;
    rhoIzz(jj,:) = props(jj).rhoIzz;
    rhoJ(jj,:) = props(jj).rhoJ;
    zcm(jj,:) = props(jj).zcm;
    ycm(jj,:) = props(jj).ycm;
    a(jj,:) = props(jj).a;
    EIyz(jj,:) = props(jj).EIyz;
    alpha1(jj,:) = props(jj).alpha1;
    alpha2(jj,:) = props(jj).alpha2;
    alpha3(jj,:) = props(jj).alpha3;
    alpha4(jj,:) = props(jj).alpha4;
    alpha5(jj,:) = props(jj).alpha5;
    alpha6(jj,:) = props(jj).alpha6;
    rhoIyz(jj,:) = props(jj).rhoIyz;
    b(jj,:) = props(jj).b;
    a0(jj,:) = props(jj).a0;
    aeroCenterOffset(jj,:) = props(jj).aeroCenterOffset;
end

elLen = el.elLen;
psi = el.psi;
theta = el.theta;
roll = el.roll;
rotationalEffects = true;

% Break out dispData
displ_s = dispData.displ_s;
displdot_s = dispData.displdot_s;
displddot_s = dispData.displddot_s;

% Break out elStorage
K11 = zeros(length(elStorage),numel(elStorage(1).K11));
K12 = zeros(length(elStorage),numel(elStorage(1).K12));
K13 = zeros(length(elStorage),numel(elStorage(1).K13));
K14 = zeros(length(elStorage),numel(elStorage(1).K14));
K15 = zeros(length(elStorage),numel(elStorage(1).K15));
K16 = zeros(length(elStorage),numel(elStorage(1).K16));
K22 = zeros(length(elStorage),numel(elStorage(1).K22));
K23 = zeros(length(elStorage),numel(elStorage(1).K23));
K24 = zeros(length(elStorage),numel(elStorage(1).K24));
K25 = zeros(length(elStorage),numel(elStorage(1).K25));
K26 = zeros(length(elStorage),numel(elStorage(1).K26));
K33 = zeros(length(elStorage),numel(elStorage(1).K33));
K34 = zeros(length(elStorage),numel(elStorage(1).K34));
K35 = zeros(length(elStorage),numel(elStorage(1).K35));
K36 = zeros(length(elStorage),numel(elStorage(1).K36));
K44 = zeros(length(elStorage),numel(elStorage(1).K44));
K45 = zeros(length(elStorage),numel(elStorage(1).K45));
K46 = zeros(length(elStorage),numel(elStorage(1).K46));
K55 = zeros(length(elStorage),numel(elStorage(1).K55));
K56 = zeros(length(elStorage),numel(elStorage(1).K56));
K66 = zeros(length(elStorage),numel(elStorage(1).K66));
M11 = zeros(length(elStorage),numel(elStorage(1).M11));
M15 = zeros(length(elStorage),numel(elStorage(1).M15));
M16 = zeros(length(elStorage),numel(elStorage(1).M16));
M22 = zeros(length(elStorage),numel(elStorage(1).M22));
M24 = zeros(length(elStorage),numel(elStorage(1).M24));
M33 = zeros(length(elStorage),numel(elStorage(1).M33));
M34 = zeros(length(elStorage),numel(elStorage(1).M34));
M44 = zeros(length(elStorage),numel(elStorage(1).M44));
M55 = zeros(length(elStorage),numel(elStorage(1).M55));
M56 = zeros(length(elStorage),numel(elStorage(1).M56));
M66 = zeros(length(elStorage),numel(elStorage(1).M66));
S11 = zeros(length(elStorage),numel(elStorage(1).S11));
S12 = zeros(length(elStorage),numel(elStorage(1).S12));
S13 = zeros(length(elStorage),numel(elStorage(1).S13));
S15 = zeros(length(elStorage),numel(elStorage(1).S15));
S16 = zeros(length(elStorage),numel(elStorage(1).S16));
S22 = zeros(length(elStorage),numel(elStorage(1).S22));
S23 = zeros(length(elStorage),numel(elStorage(1).S23));
S25 = zeros(length(elStorage),numel(elStorage(1).S25));
S26 = zeros(length(elStorage),numel(elStorage(1).S26));
S33 = zeros(length(elStorage),numel(elStorage(1).S33));
S35 = zeros(length(elStorage),numel(elStorage(1).S35));
S36 = zeros(length(elStorage),numel(elStorage(1).S36));
S55 = zeros(length(elStorage),numel(elStorage(1).S55));
S56 = zeros(length(elStorage),numel(elStorage(1).S56));
S66 = zeros(length(elStorage),numel(elStorage(1).S66));
S14_1 = zeros(length(elStorage),numel(elStorage(1).S14_1));
S14_2 = zeros(length(elStorage),numel(elStorage(1).S14_2));
S24_1 = zeros(length(elStorage),numel(elStorage(1).S24_1));
S24_2 = zeros(length(elStorage),numel(elStorage(1).S24_2));
S34_1 = zeros(length(elStorage),numel(elStorage(1).S34_1));
S34_2 = zeros(length(elStorage),numel(elStorage(1).S34_2));
S45_1 = zeros(length(elStorage),numel(elStorage(1).S45_1));
S45_2 = zeros(length(elStorage),numel(elStorage(1).S45_2));
S46_1 = zeros(length(elStorage),numel(elStorage(1).S46_1));
S46_2 = zeros(length(elStorage),numel(elStorage(1).S46_2));
S44_1 = zeros(length(elStorage),numel(elStorage(1).S44_1));
S44_2 = zeros(length(elStorage),numel(elStorage(1).S44_2));
S44_3 = zeros(length(elStorage),numel(elStorage(1).S44_3));
C12 = zeros(length(elStorage),numel(elStorage(1).C12));
C13 = zeros(length(elStorage),numel(elStorage(1).C13));
C23 = zeros(length(elStorage),numel(elStorage(1).C23));
C24 = zeros(length(elStorage),numel(elStorage(1).C24));
C25 = zeros(length(elStorage),numel(elStorage(1).C25));
C26 = zeros(length(elStorage),numel(elStorage(1).C26));
C34 = zeros(length(elStorage),numel(elStorage(1).C34));
C35 = zeros(length(elStorage),numel(elStorage(1).C35));
C36 = zeros(length(elStorage),numel(elStorage(1).C36));
C14_1 = zeros(length(elStorage),numel(elStorage(1).C14_1));
C14_2 = zeros(length(elStorage),numel(elStorage(1).C14_2));
C45_1 = zeros(length(elStorage),numel(elStorage(1).C45_1));
C45_2 = zeros(length(elStorage),numel(elStorage(1).C45_2));
C46_1 = zeros(length(elStorage),numel(elStorage(1).C46_1));
C46_2 = zeros(length(elStorage),numel(elStorage(1).C46_2));
mel = zeros(length(elStorage),numel(elStorage(1).mel));
moiel = zeros(length(elStorage),numel(elStorage(1).moiel));
xmel = zeros(length(elStorage),numel(elStorage(1).xmel));

for jj = 1:length(elStorage)
    K11(jj,:) = [elStorage(jj).K11(1,:),elStorage(jj).K11(2,:)];
    K12(jj,:) = [elStorage(jj).K12(1,:),elStorage(jj).K12(2,:)];
    K13(jj,:) = [elStorage(jj).K13(1,:),elStorage(jj).K13(2,:)];
    K14(jj,:) = [elStorage(jj).K14(1,:),elStorage(jj).K14(2,:)];
    K15(jj,:) = [elStorage(jj).K15(1,:),elStorage(jj).K15(2,:)];
    K16(jj,:) = [elStorage(jj).K16(1,:),elStorage(jj).K16(2,:)];
    K22(jj,:) = [elStorage(jj).K22(1,:),elStorage(jj).K22(2,:)];
    K23(jj,:) = [elStorage(jj).K23(1,:),elStorage(jj).K23(2,:)];
    K24(jj,:) = [elStorage(jj).K24(1,:),elStorage(jj).K24(2,:)];
    K25(jj,:) = [elStorage(jj).K25(1,:),elStorage(jj).K25(2,:)];
    K26(jj,:) = [elStorage(jj).K26(1,:),elStorage(jj).K26(2,:)];
    K33(jj,:) = [elStorage(jj).K33(1,:),elStorage(jj).K33(2,:)];
    K34(jj,:) = [elStorage(jj).K34(1,:),elStorage(jj).K34(2,:)];
    K35(jj,:) = [elStorage(jj).K35(1,:),elStorage(jj).K35(2,:)];
    K36(jj,:) = [elStorage(jj).K36(1,:),elStorage(jj).K36(2,:)];
    K44(jj,:) = [elStorage(jj).K44(1,:),elStorage(jj).K44(2,:)];
    K45(jj,:) = [elStorage(jj).K45(1,:),elStorage(jj).K45(2,:)];
    K46(jj,:) = [elStorage(jj).K46(1,:),elStorage(jj).K46(2,:)];
    K55(jj,:) = [elStorage(jj).K55(1,:),elStorage(jj).K55(2,:)];
    K56(jj,:) = [elStorage(jj).K56(1,:),elStorage(jj).K56(2,:)];
    K66(jj,:) = [elStorage(jj).K66(1,:),elStorage(jj).K66(2,:)];
    M11(jj,:) = [elStorage(jj).M11(1,:),elStorage(jj).M11(2,:)];
    M15(jj,:) = [elStorage(jj).M15(1,:),elStorage(jj).M15(2,:)];
    M16(jj,:) = [elStorage(jj).M16(1,:),elStorage(jj).M16(2,:)];
    M22(jj,:) = [elStorage(jj).M22(1,:),elStorage(jj).M22(2,:)];
    M24(jj,:) = [elStorage(jj).M24(1,:),elStorage(jj).M24(2,:)];
    M33(jj,:) = [elStorage(jj).M33(1,:),elStorage(jj).M33(2,:)];
    M34(jj,:) = [elStorage(jj).M34(1,:),elStorage(jj).M34(2,:)];
    M44(jj,:) = [elStorage(jj).M44(1,:),elStorage(jj).M44(2,:)];
    M55(jj,:) = [elStorage(jj).M55(1,:),elStorage(jj).M55(2,:)];
    M56(jj,:) = [elStorage(jj).M56(1,:),elStorage(jj).M56(2,:)];
    M66(jj,:) = [elStorage(jj).M66(1,:),elStorage(jj).M66(2,:)];
    S11(jj,:) = [elStorage(jj).S11(1,:),elStorage(jj).S11(2,:)];
    S12(jj,:) = [elStorage(jj).S12(1,:),elStorage(jj).S12(2,:)];
    S13(jj,:) = [elStorage(jj).S13(1,:),elStorage(jj).S13(2,:)];
    S15(jj,:) = [elStorage(jj).S15(1,:),elStorage(jj).S15(2,:)];
    S16(jj,:) = [elStorage(jj).S16(1,:),elStorage(jj).S16(2,:)];
    S22(jj,:) = [elStorage(jj).S22(1,:),elStorage(jj).S22(2,:)];
    S23(jj,:) = [elStorage(jj).S23(1,:),elStorage(jj).S23(2,:)];
    S25(jj,:) = [elStorage(jj).S25(1,:),elStorage(jj).S25(2,:)];
    S26(jj,:) = [elStorage(jj).S26(1,:),elStorage(jj).S26(2,:)];
    S33(jj,:) = [elStorage(jj).S33(1,:),elStorage(jj).S33(2,:)];
    S35(jj,:) = [elStorage(jj).S35(1,:),elStorage(jj).S35(2,:)];
    S36(jj,:) = [elStorage(jj).S36(1,:),elStorage(jj).S36(2,:)];
    S55(jj,:) = [elStorage(jj).S55(1,:),elStorage(jj).S55(2,:)];
    S56(jj,:) = [elStorage(jj).S56(1,:),elStorage(jj).S56(2,:)];
    S66(jj,:) = [elStorage(jj).S66(1,:),elStorage(jj).S66(2,:)];
    S14_1(jj,:) = [elStorage(jj).S14_1(1,:),elStorage(jj).S14_1(2,:)];
    S14_2(jj,:) = [elStorage(jj).S14_2(1,:),elStorage(jj).S14_2(2,:)];
    S24_1(jj,:) = [elStorage(jj).S24_1(1,:),elStorage(jj).S24_1(2,:)];
    S24_2(jj,:) = [elStorage(jj).S24_2(1,:),elStorage(jj).S24_2(2,:)];
    S34_1(jj,:) = [elStorage(jj).S34_1(1,:),elStorage(jj).S34_1(2,:)];
    S34_2(jj,:) = [elStorage(jj).S34_2(1,:),elStorage(jj).S34_2(2,:)];
    S45_1(jj,:) = [elStorage(jj).S45_1(1,:),elStorage(jj).S45_1(2,:)];
    S45_2(jj,:) = [elStorage(jj).S45_2(1,:),elStorage(jj).S45_2(2,:)];
    S46_1(jj,:) = [elStorage(jj).S46_1(1,:),elStorage(jj).S46_1(2,:)];
    S46_2(jj,:) = [elStorage(jj).S46_2(1,:),elStorage(jj).S46_2(2,:)];
    S44_1(jj,:) = [elStorage(jj).S44_1(1,:),elStorage(jj).S44_1(2,:)];
    S44_2(jj,:) = [elStorage(jj).S44_2(1,:),elStorage(jj).S44_2(2,:)];
    S44_3(jj,:) = [elStorage(jj).S44_3(1,:),elStorage(jj).S44_3(2,:)];
    C12(jj,:) = [elStorage(jj).C12(1,:),elStorage(jj).C12(2,:)];
    C13(jj,:) = [elStorage(jj).C13(1,:),elStorage(jj).C13(2,:)];
    C23(jj,:) = [elStorage(jj).C23(1,:),elStorage(jj).C23(2,:)];
    C24(jj,:) = [elStorage(jj).C24(1,:),elStorage(jj).C24(2,:)];
    C25(jj,:) = [elStorage(jj).C25(1,:),elStorage(jj).C25(2,:)];
    C26(jj,:) = [elStorage(jj).C26(1,:),elStorage(jj).C26(2,:)];
    C34(jj,:) = [elStorage(jj).C34(1,:),elStorage(jj).C34(2,:)];
    C35(jj,:) = [elStorage(jj).C35(1,:),elStorage(jj).C35(2,:)];
    C36(jj,:) = [elStorage(jj).C36(1,:),elStorage(jj).C36(2,:)];
    C14_1(jj,:) = [elStorage(jj).C14_1(1,:),elStorage(jj).C14_1(2,:)];
    C14_2(jj,:) = [elStorage(jj).C14_2(1,:),elStorage(jj).C14_2(2,:)];
    C45_1(jj,:) = [elStorage(jj).C45_1(1,:),elStorage(jj).C45_1(2,:)];
    C45_2(jj,:) = [elStorage(jj).C45_2(1,:),elStorage(jj).C45_2(2,:)];
    C46_1(jj,:) = [elStorage(jj).C46_1(1,:),elStorage(jj).C46_1(2,:)];
    C46_2(jj,:) = [elStorage(jj).C46_2(1,:),elStorage(jj).C46_2(2,:)];
    mel(jj) = elStorage(jj).mel;
    moiel(jj,:) = [elStorage(jj).moiel(1,:),elStorage(jj).moiel(2,:),elStorage(jj).moiel(3,:)];
    xmel(jj,:) = elStorage(jj).xmel(:);
end

Bogus1 = zeros(32,1);

[displ_sp1,displddot_sp1,displdot_sp1,eps_xx_0,eps_xx_z,eps_xx_y,gam_xz_0,gam_xz_y,gam_xy_0,gam_xy_z,FReaction_sp1] = structuralDynamicsTransient(rotationalEffects,...
gravityOn,...
nlOn,...
maxNumLoadSteps,...
airDensity,...
RayleighAlpha,...
RayleighBeta,...
elementOrder,...
delta_t,...
platformTurbineConnectionNodeNumber,...
tolerance,...
maxIterations,...
numpBC,...
numEl,...
Omega_j,...
OmegaDot_j,...
mel,...
moiel,...
xmel,...
Fexternal,...
Fdof,...
CN2H,...
rbData,...
jointTransform,...
conn,...
joint,...
pBC,...
x,...
y,...
z,...
ac,...
twist,...
rhoA,...
EIyy,...
EIzz,...
GJ,...
EA,...
rhoIyy,...
rhoIzz,...
rhoJ,...
zcm,...
ycm,...
a,...
EIyz,...
alpha1,...
alpha2,...
alpha3,...
alpha4,...
alpha5,...
alpha6,...
rhoIyz,...
b,...
a0,...
aeroCenterOffset,...
elLen,...
psi,...
theta,...
roll,...
displ_s,...
displdot_s,...
displddot_s,...
K11,...
K12,...
K13,...
K14,...
K15,...
K16,...
K22,...
K23,...
K24,...
K25,...
K26,...
K33,...
K34,...
K35,...
K36,...
K44,...
K45,...
K46,...
K55,...
K56,...
K66,...
M11,...
M15,...
M16,...
M22,...
M24,...
M33,...
M34,...
M44,...
M55,...
M56,...
M66,...
S11,...
S12,...
S13,...
S15,...
S16,...
S22,...
S23,...
S25,...
S26,...
S33,...
S35,...
S36,...
S55,...
S56,...
S66,...
S14_1,...
S14_2,...
S24_1,...
S24_2,...
S34_1,...
S34_2,...
S45_1,...
S45_2,...
S46_1,...
S46_2,...
S44_1,...
S44_2,...
S44_3,...
C12,...
C13,...
C23,...
C24,...
C25,...
C26,...
C34,...
C35,...
C36,...
C14_1,...
C14_2,...
C45_1,...
C45_2,...
C46_1,...
C46_2);
% rotationalEffects,...
% joint,...
% pBC,...
% x,...
% y,...
% z,...
% ac,...
% twist,...
% rhoA,...
% EIyy,...
% EIzz,...
% GJ,...
% EA,...
% rhoIyy,...
% rhoIzz,...
% rhoJ,...
% zcm,...
% ycm,...
% a,...
% EIyz,...
% alpha1,...
% alpha2,...
% alpha3,...
% alpha4,...
% alpha5,...
% alpha6,...
% rhoIyz,...
% b,...
% a0,...
% aeroCenterOffset,...
% elLen,...
% psi,...
% theta,...
% roll,...
% displ_s,...
% displdot_s,...
% displddot_s,...
% K11,...
% K12,...
% K13,...
% K14,...
% K15,...
% K16,...
% K22,...
% K23,...
% K24,...
% K25,...
% K26,...
% K33,...
% K34,...
% K35,...
% K36,...
% K44,...
% K45,...
% K46,...
% K55,...
% K56,...
% K66,...
% M11,...
% M15,...
% M16,...
% M22,...
% M24,...
% M33,...
% M34,...
% M44,...
% M55,...
% M56,...
% M66,...
% S11,...
% S12,...
% S13,...
% S15,...
% S16,...
% S22,...
% S23,...
% S25,...
% S26,...
% S33,...
% S35,...
% S36,...
% S55,...
% S56,...
% S66,...
% S14_1,...
% S14_2,...
% S24_1,...
% S24_2,...
% S34_1,...
% S34_2,...
% S45_1,...
% S45_2,...
% S46_1,...
% S46_2,...
% S44_1,...
% S44_2,...
% S44_3,...
% C12,...
% C13,...
% C23,...
% C24,...
% C25,...
% C26,...
% C34,...
% C35,...
% C36,...
% C14_1,...
% C14_2,...
% C45_1,...
% C45_2,...
% C46_1,...
% C46_2,...
% mel,...
% moiel,...
% xmel,...
% Fexternal,...
% Fdof,...
% CN2H,...
% rbData,...
% jointTransform,...
% conn,...
% gravityOn,...
% nlOn,...
% maxNumLoadSteps,...
% airDensity,...
% RayleighAlpha,...
% RayleighBeta,...
% elementOrder,...
% delta_t,...
% platformTurbineConnectionNodeNumber,...
% tolerance,...
% maxIterations,...
% numpBC,...
% numEl,...
% Omega_j,...
% OmegaDot_j);

% Reconstruct dispOut.elStrain
single_elStrain = struct('eps_xx_0',zeros(1,4),'eps_xx_z',zeros(1,4),'eps_xx_y',...
zeros(1,4),'gam_xz_0',zeros(1,4),'gam_xz_y',zeros(1,4),'gam_xy_0',zeros(1,4),'gam_xy_z',zeros(1,4));

elStrain = repmat(single_elStrain,1,numEl);

for jj = 1:mesh.numEl
    elStrain(jj).eps_xx_0(:) = eps_xx_0(jj*4-3:jj*4);
    elStrain(jj).eps_xx_z(:) = eps_xx_z(jj*4-3:jj*4);
    elStrain(jj).eps_xx_y(:) = eps_xx_y(jj*4-3:jj*4);
    elStrain(jj).gam_xz_0(:) = gam_xz_0(jj*4-3:jj*4);
    elStrain(jj).gam_xz_y(:) = gam_xz_y(jj*4-3:jj*4);
    elStrain(jj).gam_xy_0(:) = gam_xy_0(jj*4-3:jj*4);
    elStrain(jj).gam_xy_z(:) = gam_xy_z(jj*4-3:jj*4);
end
dispOut.displ_sp1 = displ_sp1;
dispOut.displddot_sp1 = displddot_sp1;
dispOut.displdot_sp1 = displdot_sp1;
dispOut.elStrain = elStrain;

toc()