export WindIORunSpec,
    windio_run_spec,
    render_windio_run_script,
    write_windio_run_script,
    build_windio_run_manifest,
    write_windio_run_manifest

struct WindIORunSpec
    modeling_options_file::String
    windio_file::String
    run_path::String
end

"""
    windio_run_spec(modeling_options_file, windio_file, run_path; create_run_path=false)

Create a reproducible, file-based WindIO run specification for
`runOWENSWINDIO(modeling_options_file, windio_file, run_path)`. File paths are
stored as absolute paths so scripts exported from the spec do not depend on the
current Julia working directory.
"""
function windio_run_spec(
    modeling_options_file::AbstractString,
    windio_file::AbstractString,
    run_path::AbstractString;
    create_run_path::Bool = false,
)
    model_file = abspath(modeling_options_file)
    design_file = abspath(windio_file)
    output_path = abspath(run_path)

    isfile(model_file) ||
        throw(ArgumentError("Modeling options file does not exist: $model_file"))
    isfile(design_file) || throw(ArgumentError("WindIO file does not exist: $design_file"))

    if create_run_path
        mkpath(output_path)
    end
    isdir(output_path) || throw(ArgumentError("Run path does not exist: $output_path"))

    return WindIORunSpec(model_file, design_file, output_path)
end

"""
    render_windio_run_script(spec)

Render a deterministic Julia script for a `WindIORunSpec`.
"""
function render_windio_run_script(spec::WindIORunSpec)
    model_literal = _julia_string_literal(spec.modeling_options_file)
    windio_literal = _julia_string_literal(spec.windio_file)
    run_path_literal = _julia_string_literal(spec.run_path)

    return join(
        [
            "# Generated by OWENS.render_windio_run_script.",
            "using OWENS",
            "",
            "modeling_options_file = $model_literal",
            "windio_file = $windio_literal",
            "run_path = $run_path_literal",
            "",
            "OWENS.runOWENSWINDIO(modeling_options_file, windio_file, run_path)",
            "",
        ],
        "\n",
    )
end

"""
    write_windio_run_script(path, spec)

Write `render_windio_run_script(spec)` to `path` and return the script text.
"""
function write_windio_run_script(path::AbstractString, spec::WindIORunSpec)
    parent = dirname(path)
    if !isempty(parent)
        mkpath(parent)
    end

    script = render_windio_run_script(spec)
    open(path, "w") do io
        write(io, script)
    end

    return script
end

"""
    build_windio_run_manifest(spec; kwargs...)

Build a run manifest for a `WindIORunSpec`, hashing the modeling-options and
WindIO input files plus any existing output/generated files passed through
`output_files` or `generated_files`.
"""
function build_windio_run_manifest(
    spec::WindIORunSpec;
    run_id = nothing,
    run_name::AbstractString = "windio-run",
    output_files = String[],
    generated_files = String[],
    parameters = OrderedCollections.OrderedDict{String,Any}(),
    metadata = OrderedCollections.OrderedDict{String,Any}(),
    warnings = String[],
    status::AbstractString = "created",
    created_at_utc = nothing,
)
    manifest = build_run_manifest(;
        run_id,
        run_name,
        project_root = spec.run_path,
        solver = "runOWENSWINDIO",
        modeling_options_file = spec.modeling_options_file,
        windio_file = spec.windio_file,
        output_files,
        generated_files,
        parameters,
        metadata,
        warnings,
        status,
        created_at_utc,
    )
    capability_gates = _windio_run_capability_gates(spec.windio_file; root = spec.run_path)
    if !isempty(capability_gates)
        manifest["capability_gates"] = capability_gates
    end
    return manifest
end

"""
    write_windio_run_manifest(path, spec; kwargs...)

Build and write a WindIO run manifest. Returns the manifest that was written.
"""
function write_windio_run_manifest(path::AbstractString, spec::WindIORunSpec; kwargs...)
    manifest = build_windio_run_manifest(spec; kwargs...)
    write_run_manifest(path, manifest)
    return manifest
end

_julia_string_literal(value::AbstractString) = repr(String(value))

function _windio_run_capability_gates(windio_file::AbstractString; root::AbstractString)
    detected = _windio_run_turbine_kind(windio_file)
    if isnothing(detected) || !_windio_run_hawt_kind(detected)
        return OrderedCollections.OrderedDict{String,Any}[]
    end

    return OrderedCollections.OrderedDict{String,Any}[OrderedCollections.OrderedDict{
        String,
        Any,
    }(
        "capability" => "hawt_aeroelastic_workflow",
        "status" => "experimental",
        "severity" => "warning",
        "source_role" => "windio",
        "source_path" => relpath(abspath(windio_file), abspath(root)),
        "detected_value" => detected,
        "message" => "WindIO declares a HAWT/axial-flow turbine. OWENS HAWT setup is experimental and validation-gated; unsupported production workflows should not run without explicit checks.",
    ),]
end

function _windio_run_turbine_kind(path::AbstractString)
    parsed = YAML.load_file(path; dicttype = OrderedCollections.OrderedDict{String,Any})
    parsed isa AbstractDict || return nothing
    for key_path in (
        ("assembly", "turbine_class"),
        ("assembly", "turbine_type"),
        ("turbine", "turbine_class"),
        ("turbine", "turbine_type"),
        ("turbine_class",),
        ("turbine_type",),
    )
        value = _windio_run_nested_value(parsed, key_path)
        value isa AbstractString || continue
        isempty(strip(value)) || return String(value)
    end
    return nothing
end

function _windio_run_nested_value(data, key_path)
    value = data
    for key in key_path
        value isa AbstractDict || return nothing
        if haskey(value, key)
            value = value[key]
        elseif haskey(value, Symbol(key))
            value = value[Symbol(key)]
        else
            return nothing
        end
    end
    return value
end

function _windio_run_hawt_kind(value::AbstractString)
    normalized = uppercase(replace(value, r"[^A-Za-z0-9]+" => ""))
    return occursin("HAWT", normalized) ||
           occursin("AXIALFLOW", normalized) ||
           normalized == "AXIAL"
end
