export WindIORunSpec, windio_run_spec, render_windio_run_script, write_windio_run_script

struct WindIORunSpec
    modeling_options_file::String
    windio_file::String
    run_path::String
end

"""
    windio_run_spec(modeling_options_file, windio_file, run_path; create_run_path=false)

Create a reproducible, file-based WindIO run specification for
`runOWENSWINDIO(modeling_options_file, windio_file, run_path)`. File paths are
stored as absolute paths so scripts exported from the spec do not depend on the
current Julia working directory.
"""
function windio_run_spec(
    modeling_options_file::AbstractString,
    windio_file::AbstractString,
    run_path::AbstractString;
    create_run_path::Bool = false,
)
    model_file = abspath(modeling_options_file)
    design_file = abspath(windio_file)
    output_path = abspath(run_path)

    isfile(model_file) ||
        throw(ArgumentError("Modeling options file does not exist: $model_file"))
    isfile(design_file) || throw(ArgumentError("WindIO file does not exist: $design_file"))

    if create_run_path
        mkpath(output_path)
    end
    isdir(output_path) || throw(ArgumentError("Run path does not exist: $output_path"))

    return WindIORunSpec(model_file, design_file, output_path)
end

"""
    render_windio_run_script(spec)

Render a deterministic Julia script for a `WindIORunSpec`.
"""
function render_windio_run_script(spec::WindIORunSpec)
    model_literal = _julia_string_literal(spec.modeling_options_file)
    windio_literal = _julia_string_literal(spec.windio_file)
    run_path_literal = _julia_string_literal(spec.run_path)

    return join(
        [
            "# Generated by OWENS.render_windio_run_script.",
            "using OWENS",
            "",
            "modeling_options_file = $model_literal",
            "windio_file = $windio_literal",
            "run_path = $run_path_literal",
            "",
            "OWENS.runOWENSWINDIO(modeling_options_file, windio_file, run_path)",
            "",
        ],
        "\n",
    )
end

"""
    write_windio_run_script(path, spec)

Write `render_windio_run_script(spec)` to `path` and return the script text.
"""
function write_windio_run_script(path::AbstractString, spec::WindIORunSpec)
    parent = dirname(path)
    if !isempty(parent)
        mkpath(parent)
    end

    script = render_windio_run_script(spec)
    open(path, "w") do io
        write(io, script)
    end

    return script
end

_julia_string_literal(value::AbstractString) = repr(String(value))
