name: Julia Format Check

on:
  pull_request:
    paths:
      - 'src/**.jl'
      - '.github/workflows/format.yml'
  push:
    paths:
      - 'src/**.jl'
      - '.github/workflows/format.yml'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(name="JuliaFormatter", version="1.0.62"))'

      - name: Check formatting in src/
        run: |
          julia -e 'using JuliaFormatter; format("src", verbose=true, check=true)'