name: Julia Format Check

on:
  pull_request:
    paths:
      - 'src/**.jl'
  push:
    paths:
      - 'src/**.jl'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Install JuliaFormatter
        run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'

      - name: Check formatting
        run: |
          julia -e '
            using JuliaFormatter
            success = format("src", verbose=true)
            if !success
              error("Code is not properly formatted. Please run JuliaFormatter locally.")
            end'
